apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name:  "aether-node-app-demo"
  description: A demo app 
  annotations:
    github.com/project-slug: rohit7533/aether-node-app-demo
    tektonci/enabled: 'true'                    # Enable Tekton for this entity
    tektonci/namespace: demo
    tektonci/cluster: bsidp-cluster
spec:
  type: service
  lifecycle: production
  owner: rohit7533
