apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: pet-clinic
  namespace: demo
  description: Spring boot application
  annotations:
    github.com/project-slug: rohit7533/aether-node-app-demo
    tektonci/enabled: 'true'                    # Enable Tekton for this entity
    tektonci/namespace: demo
    tektonci/cluster: bsidp-cluster
spec:
  type: service
  lifecycle: production
  owner: rohit7533
