apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{parameters.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{parameters.name}}
  template:
    metadata:
      labels:
        app: {{parameters.name}}
    spec:
      containers:
        - name: {{parameters.name}}
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{parameters.name}}
spec:
  type: LoadBalancer
  selector:
    app: {{parameters.name}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
